#!/usr/bin/env bash

if [ $(command -v systemctl) ]; then
    systemctl reboot
elif [ $(command -v loginctl) ]; then
    loginctl reboot
elif [ $(command -v logger) ]; then
    logger -i -i salah-compass 'Could not find a way to reboot!'
fi
